- name: Load application credentials for the deployment
  hosts: app
  connection: local
  tasks:
    - include_vars: "{{ inventory_dir }}/vars/web.yml"

- name: Install and deploy apps
  hosts: app
  roles:
    - php
    - wordpress
